### ISSUE TITLE
Self hosted server vs VS or IIS

### ISSUE THREAD

**Issue by tommyw** [kadaboum/TestCMapi#1]
Hi mate!

Thanks for the project. My back is playing up, so only half working today, though it was a good chance to look at what you've done.

Really interested by the self-host server, but couldn't get it to work. So I just right-clicked web, set it as the startup project, CTRL + F5 and... it nearly works, but errors looking for the api/list/fields. I'll try to get the self host working.

We have a lot to teach each other mate! Love the fact you've built a javascript app. Will love it more, I'm sure, once I get it running.

I presume that the functionality could be hosted in any part of any other web app? Perhaps this is worth a chat, especially if we _*are*_ going to be working together!

**Comment by tommyw** [comment]
![image](https://cloud.githubusercontent.com/assets/478656/7884622/18a9da1e-0617-11e5-8c22-2e0d4ae331fb.png)

![image](https://cloud.githubusercontent.com/assets/478656/7884685/7c5cb0ae-0617-11e5-8a1a-d0e9151f8d93.png)

![image](https://cloud.githubusercontent.com/assets/478656/7884695/91c067d8-0617-11e5-8427-2c6cf516a1d7.png)

Not sure what's going on. Same on http://127.0.0.1:9999 too...
Not sure what the problem is.

**Comment by kadaboum** [comment]
Interesting.... cigarette first, and then I'll lose some neurones ;)

**Comment by tommyw** [comment]
Cool. When you say * run testcmapi.server, I'm just starting without debugging in VS... should I be doing something else?

Have read the JS and HTML. Very tidy, clean, impressed!

**Comment by kadaboum** [comment]
Thanks mate ;)
Owin self hosted servers rock! if you want to deploy your app, you just
have to install reverse proxy in IIS and create an url rewrite rule to
127.0.0.1:9999 in IIS, so it gets open to the worl!

those are the two keys to edit in testcmapi.exe.config:

<add key="url" value="http://127.0.0.1:9999/" />
<add key="path" value="E:\TestDevProjects\TestCMAPI\web" />

the other keys are for Campaign Monitor

you can change the port it doesn't matter
the path must point to when your project is. In my case:

[image: Inline images 1]

the self hosted server includes a url rewrite middleware, so
http://127.0.0.1:9999/ should automatically redirect to htpp://
127.0.0.1:9999/index.html without you having to do anything

from your screenshot, the server is running fine, but it looks like it's
not finding the index.html file

this is what you should get:

[image: Inline images 2]

and

[image: Inline images 3]

hope that helps.

**Comment by tommyw** [comment]
Hmm, inline images didn't come through...

**Comment by tommyw** [comment]
Nobber. Typo in physical path key! Sorry LaurenT!! Working now. But thanks for the explanation. I imagine the web server is super quick? Can you host anything you want in it?

**Comment by tommyw** [comment]
Very nice work mate. Will have a bit more of a play, but attention to detail looks great.

Can I ask... without the screwing around with MVC, how long did the core functionality take you, roughly?  Anything less that 40 hours is a good answer :)

**Comment by kadaboum** [comment]
39h59mn? ;)

**Comment by tommyw** [comment]
Good time management...

**Comment by tommyw** [comment]
But really. 4 hours? 10? 20? 1?

**Comment by kadaboum** [comment]
I would say 3 to 4, could not get my head on it more than 20 minutes
straight
Most of the time was used to understand CM.
The lib didn't take too long, I've copied their sample project, cleaned it,
created the controllers. From there it's just typing ;)
I've already got a template for the server. Just had to remember how
AttributeRouting works to link that with the ajax, as I'm using signalr
99.9% of the time at the moment.

you like it?

**Comment by tommyw** [comment]
Yeah it's cool. 

Where did you get those API keys etc from? Seeing if I can connect it to another CM instance..

**Comment by tommyw** [comment]
Did you create an "app"?

**Comment by tommyw** [comment]
I see you did. Getting an exception
{"Message":"An error has occurred.","ExceptionMessage":"The CreateSend API responded with the following error - 50: Must supply a valid HTTP Basic Authorization header","ExceptionType":"System.Exception","StackTrace":"   at testcmapi.lib.Controllers.ListController.GetFields() in c:\\WRDEV\\github\\TestCMapi\\testcmapi.lib\\Controllers\\ListController.cs:line 74\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}

Do I need a call back or anything?

**Comment by kadaboum** [comment]
Yeah, I thought it would help to understand how CM works if I was creating
my own account/list etc, etc...

**Comment by tommyw** [comment]
![image](https://cloud.githubusercontent.com/assets/478656/7886109/b5aa61f0-061f-11e5-9d18-746e78c5d5aa.png)

Nice.

**Comment by kadaboum** [comment]
You have weird preferences my friend! ;)

**Comment by kadaboum** [comment]
I just need to return an empty list instead of throwing an exception

**Comment by kadaboum** [comment]
I normally would use log4net, but didn't bother. will add that too later

**Comment by tommyw** [comment]
![image](https://cloud.githubusercontent.com/assets/478656/7886130/eabaea36-061f-11e5-874e-a323d5056284.png)



ha! And option 1, option 2 is better? :-)

This is the client... http://www.woolleyandwallis.co.uk/

It didn't set my preferences though...

![image](https://cloud.githubusercontent.com/assets/478656/7886179/2f7577a4-0620-11e5-8865-46a3fc0accf2.png)

**Comment by tommyw** [comment]
No need to add logging. I use NLog, but very similar.

Don't spend more than another hour on it... I think you've proven that you can research, consume and build. We'll be in touch soon bud!

**Comment by kadaboum** [comment]
nice, I like the design!

**Comment by kadaboum** [comment]
Don't worry mate, I'm not doing it for your test, just to have a clean nice
project on github

**Comment by kadaboum** [comment]
my ocd's kicking again, can't leave it unfinished!

**Comment by tommyw** [comment]
This is another going live on Monday
http://burstowhewett.u2.wrvc.co.uk
Another live one
http://www.bellmans.co.uk
And another nearly live
http://canterbury.u2.wrvc.co.uk
Becoming a good line of business for us!!!

http://www.webreality.co.uk/tag/bidmaster-auction-software

**Comment by tommyw** [comment]
Ha. I'm OCD-less. But fussy nonetheless!

**Comment by tommyw** [comment]
Have a good weekend buddy. We're out for the FA cup final tomorrow if you're keen?

Feel free to delete this thread, now!!!

**Comment by kadaboum** [comment]
Have a good weekend,
Might text you guys tomorrow if I can get the bed's frame for the van
sorted.
Was supposed to chop some wood tonight... bloody weather!
